### PR TITLE
Fix: minor typos

### PR DESCRIPTION
**Pull request by omahs**
Fix: minor typos

### CODE REVIEW

**Comment by sadrasabouri** [comment]
Thanks for your edit. I just changed the target branch to `dev` instead of `master`. Please also update the `CHANGELOG.md` too.

Afterall It seems OK to me. @sepandhaghighi please take a look at it and it if looks fine merge it.

**Comment by sadrasabouri** [comment]
Thanks for your edit. I changed the target branch to `dev` instead of `master`. Please also update the `CHANGELOG.md` too.

After all, It seems OK to me. @sepandhaghighi please take a look at it and it if looks fine merge it.

**Comment by sadrasabouri** [comment]
Thanks for your edit. I changed the target branch to `dev` instead of `master`. Please also update the `CHANGELOG.md` too.

After all, It seems OK to me. @sepandhaghighi please take a look at it and it if looks fine merge it.

**Comment by omahs** [comment]
@sadrasabouri Just updated!

**Comment by sadrasabouri** [comment]
> @sadrasabouri Just updated!

Thanks, but you put it in the wrong place.
Add a `Changed` subsection below the `[Unreleased]` section and write down your change. Also, I believe `README.md updated` would be enough.

**Comment by omahs** [comment]
@sadrasabouri Sorry, should be good now

**Review by sadrasabouri — APPROVED** [review]
Great thanks.

**Review by sepandhaghighi — APPROVED** [review]

**Pull request merged**
