### PR TITLE
`demo.ipynb` updated

### PR DESCRIPTION
**Pull request by sepandhaghighi**
#### What does this implement/fix? Explain your changes.
- `demo.ipynb` updated

### CODE REVIEW

**Review by sadrasabouri — COMMENTED** [review]
LGTM, Just a tiny point. Why did you remove `.` from the end of all sentences?
If it's for consistency, I prefer to have `.` at the end of sentences.
If you think this comment is not applicable, simply merge it. The rest is OK.

**Comment by sepandhaghighi** [comment]
> LGTM, Just a tiny point. Why did you remove `.` from the end of all sentences? If it's for consistency, I prefer to have `.` at the end of sentences. If you think this comment is not applicable, simply merge it. The rest is OK.

Just for consistency.
Fixed in https://github.com/sepandhaghighi/samila/pull/224/commits/088e9593f60955d6c4355787efd0c50ff20c5424

**Comment by sadrasabouri** [comment]
> > LGTM, Just a tiny point. Why did you remove `.` from the end of all sentences? If it's for consistency, I prefer to have `.` at the end of sentences. If you think this comment is not applicable, simply merge it. The rest is OK.
> 
> Just for consistency. Fixed in [088e959](https://github.com/sepandhaghighi/samila/commit/088e9593f60955d6c4355787efd0c50ff20c5424)

Some sentences starting with ℹ️ have `.` and some don't. Please make them consistent too.

**Comment by sepandhaghighi** [comment]
> > > LGTM, Just a tiny point. Why did you remove `.` from the end of all sentences? If it's for consistency, I prefer to have `.` at the end of sentences. If you think this comment is not applicable, simply merge it. The rest is OK.
> > 
> > 
> > Just for consistency. Fixed in [088e959](https://github.com/sepandhaghighi/samila/commit/088e9593f60955d6c4355787efd0c50ff20c5424)
> 
> Some sentences starting with ℹ️ have `.` and some don't. Please make them consistent too.

Fixed in https://github.com/sepandhaghighi/samila/pull/224/commits/8748647fd27b5efbf664580181e9c1a4d1a78dcf

**Review by sadrasabouri — APPROVED** [review]
LGTM

**Pull request merged**
