### PR TITLE
Demo notebook

### PR DESCRIPTION
**Pull request by evanofslack**
#### Reference Issues/PRs

#77 

#### What does this implement/fix? Explain your changes.

Simple Jupyter Notebook demo covering the same content in the README.md of this project. 

#### Any other comments?

I created this notebook to get familiar with the library and thought it might be useful for others. I plan to create more exploratory notebooks in the future.

### CODE REVIEW

**Comment by evanofslack** [comment]
I see there is active development on the dev branch, should I make a pull request to that branch instead? @sepandhaghighi

**Comment by sadrasabouri** [comment]
Thank for your efforts. Well done.
Yes you should PR to the `dev` branch. (as we mentioned at the end of the [CONTRIBUTING.md](https://github.com/sepandhaghighi/samila/blob/master/.github/CONTRIBUTING.md))

**Review by sadrasabouri — APPROVED** [review]
Good Job :100: 
@sepandhaghighi Please take a look at it. If everything is OK then we'll merge it.

**Review by sepandhaghighi — APPROVED** [review]
LGTM 💯

**Pull request merged**
